organization = "g-ke"
workspace    = "mlops-stack-1"
region       = "us-east-1"
tag_value    = "MLOps-Stack"
tag_key      = ""Project""
ecr_image    = "343725977869.dkr.ecr.us-east-1.amazonaws.com/mlops-stack-1"